# Generated by Django 4.1 on 2022-12-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_projeto", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tesouro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=45, unique=True)),
                ("quantidade", models.IntegerField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("img_tesouro", models.ImageField(null=True, upload_to="imgs")),
            ],
        ),
    ]
