# Generated by Django 4.1 on 2022-12-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_projeto", "0002_tesouro"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("data_nascimento", models.DateField()),
            ],
        ),
    ]
